global:
  serving:
    monitoring:
      enabled: true
      elasticsearch:
        enabled: true
      prometheus:
        enabled: true
      zipkin:
        enabled: true
  istio:
    namespace: "istio-system"

activator:
  name: "activator"
  replicas: 1
  image:
    repository: "docker.io/ibmcom/knative-serving-cmd-activator-ppc64le" #"gcr.io/knative-releases/github.com/knative/serving/cmd/activator@sha256"
    tag: "latest" #"5c154bf65e435b7e176f27ac4dcf3bc324678f2580c3cf6541901b5de169a136"

autoscaler:
  name: "autoscaler"
  serviceAccount:
    name: "autoscaler"
  image:
    repository: "docker.io/ibmcom/knative-serving-cmd-autoscaler-ppc64le" #"gcr.io/knative-releases/github.com/knative/serving/cmd/autoscaler@sha256"
    tag: "latest" #"8efaffcff9cc078a9a8e4a54fe88cc2ff8036fc189589a849a1ccec8a423d63f"

fluentd:
  image:
    repository: "docker.io/ibmcom/fluentd-elasticsearch-ppc64le" #"k8s.gcr.io/fluentd-elasticsearch"
    tag: "latest" #"v2.0.4"

queueProxy:
  image:
    repository: "docker.io/ibmcom/knative-serving-cmd-queue-ppc64le" #"gcr.io/knative-releases/github.com/knative/serving/cmd/queue@sha256"
    tag: "latest" #"df0b85347195877985d4ce91daf002febeec50c2d845b58a0a7093d8cdc7c34e"

controller:
  name: "controller"
  serviceAccount:
    name: "controller"
  image:
    repository: "docker.io/ibmcom/knative-serving-cmd-controller-ppc64le" #"gcr.io/knative-releases/github.com/knative/serving/cmd/controller@sha256"
    tag: "latest" #"0c3a179ba49bb53bb51f944013f61349d9a94b3ecf5cb75e5df37dec6d0aef79"

ingressGateway:
  name: "knative-ingressgateway"
  type: "LoadBalancer"
  image:
    repository: "docker.io/ibmcom/istio-proxy" #"docker.io/istio/proxyv2"
    tag: "0.8.0" #"1.0.2"

webhook:
  name: "webhook"
  image:
    repository: "docker.io/ibmcom/knative-serving-cmd-webhook-ppc64le" #"gcr.io/knative-releases/github.com/knative/serving/cmd/webhook@sha256"
    tag: "latest" #"1b4320c1d3d70adf4614cd7859082549630c2c3cda19176400673b8cc8df8a7d"
