controller:
  name: "kafka-channel-controller"
  serviceAccount:
    name: "kafka-channel-controller"
  bootstrapServers: ""
  image:
    repository: "docker.io/ibmcom/knative-eventing-pkg-provisioners-kafka-cmd-controller-ppc64le" #"gcr.io/knative-releases/github.com/knative/eventing/pkg/provisioners/kafka/cmd/controller@sha256"
    tag: "latest" #"c55c577048f02a37391cab8624def297aaa9c1392a788ac37dc0d57f840f1401"

dispatcher:
  name: "kafka-channel-dispatcher"
  serviceAccount:
    name: "kafka-channel-dispatcher"
  image:
    repository: "docker.io/ibmcom/knative-eventing-pkg-provisioners-kafka-cmd-dispatcher-ppc64le" #"gcr.io/knative-releases/github.com/knative/eventing/pkg/provisioners/kafka/cmd/dispatcher@sha256"
    tag: "latest" #"37ede90fc4434a3d8e330702a4c51be737a50d950456403df6744aa8faa925ca"
