{{- if .Values.persistence.dataNode.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "hadoop.fullname" . }}-hdfs-dn
  labels:
    app: {{ template "hadoop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: hdfs-dn
spec:
  {{- if .Values.persistence.useDynamicProvisioning }}
  storageClassName: {{ default nil .Values.persistence.dataNode.storageClassName | quote }}
  {{ else }}
  storageClassName: ""
  {{- end }}
  accessModes:
    - {{ .Values.persistence.dataNode.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataNode.size | quote }}
  {{- if .Values.persistence.useDynamicProvisioning  }}
  selector:
    matchLabels:
      assign-to: "hdfs-dn"
  {{- end }}
{{- end }}




