appVersion: 0.8.0
description: Chaoskube periodically kills random pods in your Kubernetes cluster.
engine: gotpl
home: https://github.com/linki/chaoskube
icon: https://github.com/ppc64le/charts/tree/master/logo/ibm-default-icon.svg?sanitize=true
keywords:
  - adapter
  - chaoskube
  - Limited
  - ppc64le
  - Tools
  - ICP
maintainers:
- email: smohite@us.ibm.com
  name: IBM ISV Team
name: ibm-chaoskube
sources:
- https://github.com/linki/chaoskube
version: 0.7.0
tillerVersion: '>=2.7.2'
