controller:
  name: "in-memory-channel-controller"
  serviceAccount:
    name: "in-memory-channel-controller"
  image:
    repository: "docker.io/ibmcom/knative-eventing-pkg-controller-eventing-inmemory-controller-ppc64le" #"gcr.io/knative-releases/github.com/knative/eventing/pkg/controller/eventing/inmemory/controller@sha256"
    tag: "latest" #"85a6954a9ab118872f6826425b213e57589de8f9f2ac97d31aef5d5022104532"
  
dispatcher:
  name: "in-memory-channel-dispatcher"
  replicas: 1
  serviceAccount:
    name: "in-memory-channel-dispatcher"
  image:
    repository: "docker.io/ibmcom/knative-eventing-cmd-fanoutsidecar-ppc64le" #"gcr.io/knative-releases/github.com/knative/eventing/cmd/fanoutsidecar@sha256"
    tag: "latest" #"a04bdbe0ffad3c47286ebfb961648e9f1d2b366aea243e9ea1ae591e706de06d"
