apiVersion: v1
appVersion: "1.0"
description: Collectd-exporter
engine: gotpl
name: ibm-collectd
icon: https://github.com/ppc64le/charts/tree/master/logo/collectd.png?sanitize=true
keywords:
  - Limited
  - ppc64le
  - Tools
  - ICP
  - collectd
maintainers:
- email: smohite@us.ibm.com
  name: IBM ISV Team
sources:
- https://hub.docker.com/r/ibmcom/collectd-exporter-ppc64le/
tillerVersion: '>=2.7.2'
version: 0.1.0
